# Продукты и программы Perfect Organic
# Формат: "Название как в тексте" -> "ссылка на страницу"
# Бот автоматически превращает названия в кликабельные ссылки

PRODUCTS = {
    "МультиМинералс74":         "https://perfect-org.ru/multiminerals74",
    "MultiMinerals74":           "https://perfect-org.ru/multiminerals74",
    "Морской Магний":            "https://perfect-org.ru/morskoy-magniy",
    "Mineral Diet Base":         "https://perfect-org.ru/mineral-diet-base",
    "Хлорелла":                  "https://perfect-org.ru/hlorella",
    "Amla Extra":                "https://perfect-org.ru/amla-extra",
    "Amla Light":                "https://perfect-org.ru/amla-light",
    "Total Energy Абрикос":      "https://perfect-org.ru/total-energy-abrikos",
    "Total Energy Ваниль":       "https://perfect-org.ru/total-energy-vanil",
    "Total Energy Шоколад":      "https://perfect-org.ru/total-energy-chokolad",
    "Total Energy Малина":       "https://perfect-org.ru/total-energy-malina",
    "Total Energy Пина Колада":  "https://perfect-org.ru/total-energy-pina-kolada",
    "Total Energy Кофе":         "https://perfect-org.ru/total-energy-kofe",
    "K-M Beauty Youth":          "https://perfect-org.ru/k-m-beauty-youth-raspberry",
    "Крем J for J":              "https://perfect-org.ru/krem-j-for-j",
    "Гермес Крем":               "https://perfect-org.ru/germes-krem",
    "Detox Oil":                 "https://perfect-org.ru/detox-oil",
    "Напиток для Суставов":      "https://perfect-org.ru/napitok-dlya-sustavov",
    "Triplex Result":            "https://perfect-org.ru/triplex-result",
    "Глуммунофэрон":             "https://perfect-org.ru/glummunoferon-15",
    "Preventor LC":              "https://perfect-org.ru/preventor-lc",
    "Perfect C":                 "https://perfect-org.ru/perfect-c",
    "5-HTP Helper":              "https://perfect-org.ru/5-htp-helper",
    "Бальзам для Сосудов":       "https://perfect-org.ru/balzam-dlya-sosudov",
    "Tanker 15":                 "https://perfect-org.ru/tanker-15-150",
    "Tanker 500":                "https://perfect-org.ru/tanker-15-500",
    "GoodBak":                   "https://perfect-org.ru/goodbak",
    "Гелмонет Капсулы":          "https://perfect-org.ru/gelmonet-kapsuly-banka",
    "Гелмонет Сироп":            "https://perfect-org.ru/gelmonet-sirop",
    "Эсфолип":                   "https://perfect-org.ru/dobavka-pishevaya-esfolip",
    "Максэнзим":                 "https://perfect-org.ru/maksehnzim",
    "Andro Pro":                 "https://perfect-org.ru/andro-pro",
    "Alfa XT":                   "https://perfect-org.ru/alfa-xt",
    "Гермес 30":                 "https://perfect-org.ru/germes30",
    "Климанет":                  "https://perfect-org.ru/klimanet",
    "Дживана":                   "https://perfect-org.ru/dzhivana",
    "Диоп Три":                  "https://perfect-org.ru/diop-tri-kapsuly",
    "Диоп Три Тоник":            "https://perfect-org.ru/diop-tri-tonik-dlya-glaz",
    "Урологический сбор 1":      "https://perfect-org.ru/urologicheskiy-1",
    "Урологический сбор 2":      "https://perfect-org.ru/urologicheskiy-2",
    "Урологический сбор 3":      "https://perfect-org.ru/urologicheskiy-3",
    "КЕД 7":                     "https://perfect-org.ru/ked-7",
    "КЕД 10":                    "https://perfect-org.ru/ked-10",
    "КЕД 11":                    "https://perfect-org.ru/ked-11",
    "Pavitra Green":             "https://perfect-org.ru/pavitra-green",
    "Pavitra Blue":              "https://perfect-org.ru/pavitra-blue",
    "Pavitra Orange":            "https://perfect-org.ru/pavitra-orange",
    "Комплекс Pavitra":          "https://perfect-org.ru/kompleks-pavitra",
    "Рутрой 1":                  "https://perfect-org.ru/rutroy-1",
    "Рутрой 2":                  "https://perfect-org.ru/rutroy-2",
    "Рутрой 3":                  "https://perfect-org.ru/rutroy-3",
    "Рутрой 4":                  "https://perfect-org.ru/rutroy-4",
    "Рутрой 5":                  "https://perfect-org.ru/rutroy-5",
    "Суп Говядина":              "https://perfect-org.ru/sup-govyadina",
    "Суп Грибной":               "https://perfect-org.ru/sup-gribnoy",
    "Суп Куриный":               "https://perfect-org.ru/sup-kuriniy",
    "Суп Томатный":              "https://perfect-org.ru/sup-tomatniy",
    "Семена Чиа":                "https://perfect-org.ru/semena-chia",
    "Масло Чиа":                 "https://perfect-org.ru/maslo-chia",
    "Масло Чёрного Тмина":       "https://perfect-org.ru/maslo-chernogo-tmina",
    "Мидиактив Форте":           "https://perfect-org.ru/midiaktiv-forte",
    "Сумедха":                   "https://perfect-org.ru/sumedha",
    "Аскондум":                  "https://perfect-org.ru/asconodum",
    "Даруна":                    "https://perfect-org.ru/daruna",
    "Даруна Бокс":               "https://perfect-org.ru/daruna-box",
    "Насисол 10":                "https://perfect-org.ru/nasisol-10",
    "Насисол 30":                "https://perfect-org.ru/nasisol-30",
    "Shock Fire":                "https://perfect-org.ru/shock-fire",
    "Граф Картридж":             "https://perfect-org.ru/graf-cartrig",
    "Граф Графин Blue":          "https://perfect-org.ru/graf-grafin-blue",
    "Разделитель":               "https://perfect-org.ru/razdelitel-500",
    "Программа Питание":         "https://perfect-org.ru/pitanie",
    "Программа Сердце":          "https://perfect-org.ru/serdce",
    "Программа Суставы":         "https://perfect-org.ru/sustavy",
    "Программа Детокс":          "https://perfect-org.ru/detox",
    "Программа Иммунитет":       "https://perfect-org.ru/imunitet",
    "Программа Онко":            "https://perfect-org.ru/onko",
}

# Короткие варианты и общие слова для поиска в тексте
PRODUCT_ALIASES = {
    # Минералы
    "минералы":        "https://perfect-org.ru/multiminerals74",
    "минерал":         "https://perfect-org.ru/multiminerals74",
    "мультиминерал":   "https://perfect-org.ru/multiminerals74",
    # Коктейли Total Energy
    "Total Energy":    "https://perfect-org.ru/total-energy-abrikos",
    "коктейль":        "https://perfect-org.ru/total-energy-abrikos",
    "коктейли":        "https://perfect-org.ru/total-energy-abrikos",
    "коктелей":        "https://perfect-org.ru/total-energy-abrikos",
    "коктейлей":       "https://perfect-org.ru/total-energy-abrikos",
    # Коллаген
    "коллаген":        "https://perfect-org.ru/k-m-beauty-youth-raspberry",
    "коллагена":       "https://perfect-org.ru/k-m-beauty-youth-raspberry",
    "коллагеном":      "https://perfect-org.ru/k-m-beauty-youth-raspberry",
    # Бренд (все варианты написания)
    "Perfect Organic":   "https://perfect-org.ru/",
    "Перфект Органик":   "https://perfect-org.ru/",
    "перфекторганик":    "https://perfect-org.ru/",
    "PerfectOrganic":    "https://perfect-org.ru/",
    # Amla — русские варианты
    "Amla":              "https://perfect-org.ru/amla-extra",
    "Амла":              "https://perfect-org.ru/amla-extra",
    "Амло":              "https://perfect-org.ru/amla-extra",
    # Русские названия английских продуктов
    "ГудБак":            "https://perfect-org.ru/goodbak",
    "Детокс Ойл":        "https://perfect-org.ru/detox-oil",
    "детокс":            "https://perfect-org.ru/detox-oil",
    "Андро Про":         "https://perfect-org.ru/andro-pro",
    "Алфа ХТ":           "https://perfect-org.ru/alfa-xt",
    "Превентор":         "https://perfect-org.ru/preventor-lc",
    "Перфект Си":        "https://perfect-org.ru/perfect-c",
    "Танкер":            "https://perfect-org.ru/tanker-15-150",
    "Павитра":           "https://perfect-org.ru/kompleks-pavitra",
    "Шок Файр":          "https://perfect-org.ru/shock-fire",
    # Короткие формы продуктов
    "Мидиактив":         "https://perfect-org.ru/midiaktiv-forte",
    "Медиактив":         "https://perfect-org.ru/midiaktiv-forte",
    "Граф":              "https://perfect-org.ru/graf-cartrig",
    # Остальные
    "хлорелла":          "https://perfect-org.ru/hlorella",
    "хлореллы":          "https://perfect-org.ru/hlorella",
    "Гелмонет":          "https://perfect-org.ru/gelmonet-kapsuly-banka",
    "Pavitra":           "https://perfect-org.ru/kompleks-pavitra",
    "Tanker":            "https://perfect-org.ru/tanker-15-150",
    "магний":            "https://perfect-org.ru/morskoy-magniy",
    "магния":            "https://perfect-org.ru/morskoy-magniy",
    "магнием":           "https://perfect-org.ru/morskoy-magniy",
}
